### ISSUE TITLE
bug: se si rimuove la porta seriale onos si termina

### ISSUE THREAD

**Issue by onosAdmin** [OnosTeam/onos#26]
Se all'avvio di onos si rimuove la porta usb seriale onos da errore:
class Serial_connection_Handler destroyed
class arduinoserial destroyed
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
executed changeWebObjectType() with :wifi0_Plug6way0002
Traceback (most recent call last):
  File "webserver.py", line 1373, in <module>
    changeWebObjectType(a.getName(),a.getType())  #i call this in order to setup the node io conf for the webobjects
  File "webserver.py", line 411, in changeWebObjectType
    hardware.setHwPinMode(node_address,pins_to_set[0],"DOUTPUT")
NameError: global name 'hardware' is not defined

**Comment by onosAdmin** [comment]
Risolto! in più adesso se si rimuove la seriale e poi la si ricollega onos se ne accorge e ricomincia ad usarla correttamente!!!!
